### ISSUE TITLE
Test and prepare RedDeer for JDK11

### ISSUE THREAD

**Issue by jkopriva** [eclipse/reddeer#1975]

**Comment by odockal** [comment]
Source and target java changed to 11 in 
* https://github.com/eclipse/reddeer/commit/47496c3b325e8133ac0803d363d261efdcfd14c8
Tests fixed in 
* https://github.com/eclipse/reddeer/commit/7b70b98d9e7be03b705971e403d4d8f55a46ec70
* https://github.com/eclipse/reddeer/commit/6ab350b5410e33492efcff2f24f1af9aaab5c9c1
* https://github.com/eclipse/reddeer/commit/c1eeae63475ad4c2a16c06c1bec277fdbc20a1eb

Jenkins jobs default jdk tool moved to openjdk 11.
Released in milestone 3.1.0.M3.
