### ISSUE TITLE
New condition: TreeHasItem

### ISSUE THREAD

**Issue by jkopriva** [eclipse/reddeer#2034]

**Comment by jkopriva** [comment]
There is similar condition TreeContainsItem

**Comment by odockal** [comment]
I have add an constructor that takes only one parameter - item path (String []), the tree used will be defined by new DefaultTree() instead of doing this when initializing the TreeContainsItem. What you have done in OS plugin, it searches only on the first level. So I do not think this would be proper implementation in RD. TreeContainsItem offers broader functionality.
