### ISSUE TITLE
Missing Jackson dependency when trying to use Reddeer with Eclipse I-builds update site

### ISSUE THREAD

**Issue by henryju** [eclipse/reddeer#2154]
Hi,

We are testing our plugin against multiple versions of Eclipse, and also with latest milestone. It was working fine until latest Eclipse cycle. It seems something has changed, because one dependency is missing (com.fasterxml.jackson.core.jackson-core). I guess it was previously part of the Eclipse repo, and has been removed.
Is it expected? Shouldn't it be provided in Reddeer update site?
![image](https://user-images.githubusercontent.com/281596/149914031-fcf5cff7-b79b-4f2e-b0da-5baa0f494a10.png)

**Comment by odockal** [comment]
@henryju Hi, thanks for reporting. I will take a look.

**Comment by odockal** [comment]
@henryju Interesting, it is true that we got rid of transitive dependencies as the whole reddeer bundle was around 400 MB just because we included transitive deps into release. And all of them are still included in eclipse update sites. So I added repository references [here]. Now it is possible to install reddeer from p2 into eclipse with only a couple of MBs. I am curious why it does not work for you, the missing package is included in the eclipse [update site].

[here]: https://github.com/eclipse/reddeer/pull/2148/commits/b0ace5059849ca92d9d8faf806302a0883a30c0a
[update site]: https://download.eclipse.org/staging/2021-12/plugins/

**Comment by henryju** [comment]
Sorry, I forgot that milestone repositories are no more a thing. I was talking about I-build repo: https://download.eclipse.org/eclipse/updates/4.23-I-builds/I20220129-1800/plugins/
You can see that the jackson dependency is not there.

**Comment by odockal** [comment]
@henryju I am looking at from where I was taking com.fasterxml deps and it is either in eclipse [orbit update site] or in eclipse staging/release [simrel update site], but it seems it was never a part of eclipse updates as you mention. I guess that adding one of these update sites should fix the problem.

[orbit update site]: https://download.eclipse.org/tools/orbit/downloads/latest-S/
[simrel update site]: https://download.eclipse.org/staging/2022-03/plugins/

**Comment by henryju** [comment]
Yes, that's what I [ended up doing](https://github.com/SonarSource/sonarlint-eclipse/blob/dc3b24710b5ee62078238422e068d85d14f73140/its/target-platforms/ibuilds.target#L30). This is good enough for me, so feel free to close this issue.

> I guess it was previously part of the Eclipse repo, and has been removed.
I was possibly wrong with this statement. We changed from the "[milestone](http://download.eclipse.org/eclipse/updates/milestones)" repository to the "[ibuild](https://download.eclipse.org/eclipse/updates/I-builds)" one, so it is likely there is not the same content.

**Comment by odockal** [comment]
@henryju Could be! also, as I said I have removed bundling of all of the deps in reddeer itself, so that could have something in common as well. Anyway, thanks and I will close the issue.
