### ISSUE TITLE
ConsoleHasLabel should not keep a static instance of the ConsoleView

### ISSUE THREAD

**Issue by henryju** [eclipse/reddeer#2162]
If you open a Console view, then close it, and then try to open a new Console again, `ConsoleHasLabel` will stop working properly as it will still be referring to the old `ConsoleView`

To reproduce, you can do something like:

```java
Matcher<String> textMatcher = StringEndsWith.endsWith("Java Stack Trace Console")

// First run
ConsoleView console1 = new ConsoleView();
console1.open();
var menu = new ToolItemMenuItem(new DefaultToolItem(console1.getCTabItem().getFolder(), "Open Console"), textMatcher);
menu.select();
new WaitUntil(new ConsoleHasLabel(textMatcher));
console1.close();

// Second run
ConsoleView console2 = new ConsoleView();
console2.open();
var menu = new ToolItemMenuItem(new DefaultToolItem(console2.getCTabItem().getFolder(), "Open Console"), textMatcher);
menu.select();
new WaitUntil(new ConsoleHasLabel(textMatcher)); // Will fail because ConsoleHasLabel still refers to console1
```

I think ConsoleHasLabel should not [cache](https://github.com/eclipse/reddeer/blob/fd6d8b77510e8969ea9fef85d70563bfd23ead0c/plugins/org.eclipse.reddeer.eclipse/src/org/eclipse/reddeer/eclipse/condition/ConsoleHasLabel.java#L29) the ConsoleView, but instead take it as constructor parameter:

```java
new WaitUntil(new ConsoleHasLabel(consoleView, textMatcher));
```

**Comment by henryju** [comment]
> When you are creating new instance of ConsoleHasLabel it also initiates new instance for ConsoleView

This is not what I read in the code:
https://github.com/eclipse/reddeer/blob/fd6d8b77510e8969ea9fef85d70563bfd23ead0c/plugins/org.eclipse.reddeer.eclipse/src/org/eclipse/reddeer/eclipse/condition/ConsoleHasLabel.java#L46

Your test passes because the console1 is not really closed, and when you open console2, what you get is the same cached view. I'm not totally sure of the behavior (and it might depends on Eclipse version). This SO thread said that closing the last instance of a view in all perspective should really dispose it, but here it doesn't seem to work (could it be because Reddeer is keeping a reference to the console view?). The only way I found to properly dispose the console view is to close the Console before closing the Console View. Then you can reproduce the issue I was facing:


```
Matcher<String> textMatcher = StringEndsWith.endsWith("Java Stack Trace Console");
Matcher<String> textMatcher2 = StringEndsWith.endsWith("CVS");

// First run
ConsoleView console1 = new ConsoleView();
console1.open();
var menu = new ToolItemMenuItem(new DefaultToolItem(console1.getCTabItem().getFolder(), "Open Console"), textMatcher);
menu.select();
new WaitUntil(new ConsoleHasLabel(textMatcher));
new DefaultToolItem(console1.getCTabItem().getFolder(), "Close Console").click(); // Close the console to ensure the view will be disposed
console1.close();

// Second run
ConsoleView console2 = new ConsoleView();
console2.open();
var menu2 = new ToolItemMenuItem(new DefaultToolItem(console2.getCTabItem().getFolder(), "Open Console"), textMatcher2);
		menu2.select();
// we need to change condition to adjust to the new expected label
		new WaitUntil(new ConsoleHasLabel(textMatcher2)); // passes
```

**Comment by odockal** [comment]
I guess that the problem is what do you expect from reddeer. It is not supposed to change the behavior of eclipse object API but rather provide a means to use it. Almost like using only visible elements via UI. 

So the ConsoleHasLabel/ConsoleView only initiates Console View and provides what is there, it should not really influence or bypass what eclipse logic does with that object. 

Maybe we just do not understand each other. back to your test, I tried the code, it still works. I think it is because the nature how consoles works in eclipse. RedDeer should only mimic user interaction via eclipse object API.

**Comment by henryju** [comment]
Here is a reproducer:
[com.sonarsource.reddeer.zip](https://github.com/eclipse/reddeer/files/8133088/com.sonarsource.reddeer.zip)
Simply run `mvn clean verify` and it should fail.

**Comment by odockal** [comment]
I guess I see the point, and you are right. Nevertheless, it still works fine, but not due to use of static member (as really could be an issue in different cases) but rather thanks to how the label text is gathered in [getConsoleLabel](https://github.com/eclipse/reddeer/blob/c57b05ef8a34aea8b532bb292f24875b83696710/plugins/org.eclipse.reddeer.eclipse/src/org/eclipse/reddeer/eclipse/ui/console/ConsoleView.java#L242). So I will rewrite the code, but I cannot break the api so the change will be different than suggested. 

Thanks for you time to explaining this issue to me ;)
